### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by wzkxv** [NerduMiner/bfntoolkit#2]
![image](https://user-images.githubusercontent.com/116641579/197755567-628f89e8-39b5-42fa-9e72-a06628147ca9.png)
![image](https://user-images.githubusercontent.com/116641579/197755579-ea32c568-4fe6-459f-afb0-63f6e0924964.png)
The file headers of the two files are inconsistent.I use the tool you provided to generate the file header of FONTbfn1.|9 by default, and I would like to know if it is possible to generate the file of the FONTbfn1.2 file header and the FONTbfn1.3 file header. thank you for your support.

**Comment by NerduMiner** [comment]
Do you know if there are any marginal differences between the different file header versions? If there aren't any, I can see about making the JSON recognize the version of the bfn for building.

**Comment by NerduMiner** [comment]
Actually, I just refreshed myself about the BFN format. What you are looking at is actually the file size indicator of the header. There is only one version of the BFN header and it always starts with "FONTbfn1" sometimes the size part of the header can make it look like theres a more specific version, but thats not the case. Hope this clears things up so long as your edited bfn file works in game!

**Comment by wzkxv** [comment]
Thank you！！
